version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: patient-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: desarrollador
      POSTGRES_PASSWORD: desarrollador
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - patient-network

  patient-service:
    build: .
    container_name: patient-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: desarrollador
      SPRING_DATASOURCE_PASSWORD: desarrollador
    networks:
      - patient-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  patient-network:
    driver: bridge
