server:
  port: 8082

spring:
  application:
    name: clinical-record-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinicaldb
      # Para autenticaci√≥n:
      # uri: mongodb://username:password@localhost:27017/clinicaldb
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    '[com.riavet.clinicalrecordservice]': DEBUG
    '[org.springframework.data.mongodb]': DEBUG
